name: CI-CD-pipeline-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME : "githubactionstesting"
  EB_APPLICATEION_NAME      : "FlaskApplication"
  EB_ENVIROMENT_NAME        : "FlaskApplication-env-1"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-central-1"

on:
  push:
    branches:
    - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Create zip deployment package
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
